services:
  - type: web
    name: expense-tracker
    runtime: python
    buildCommand: ""
    startCommand: "gunicorn run:app"
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
